# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWFhZWFhNmFiYmU2OTYwYmE1NGQzNzNkOWVmYWU0Y2JlMmUyMTNmN2JmMjEyMWQ4NGUwMjQzOWJhZmEwZTViMDk5ZDRhZjJjYWJjZjI1N2MyOTRlZTRlNjUyN2Y0YjNlOWRhNTJmZGIzMjY4N2U5ZjAzZDc5NDUxNTM0Yjk1MTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
